%For runtime instantiated GameObject, only the prefab mapping is provided. Use that one substituting the gameobject name accordingly.
 %Sensors.
%lumenSentinelSensor_CurrentHealth(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_IsDead(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_currentStateName(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Z(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Y(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_X(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_name(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyId(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_ReasoningStyleType(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_minBatteryBeforeRecharge(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_shootingDistance(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_batteryIdleDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_batteryWalkingDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_batteryRunningDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_batteryPrimaryWeaponDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_batterySecondaryWeaponDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_primaryAmmo(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_secondaryAmmo(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_minBatteryBeforeRecharge(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_primaryAmmo(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_secondaryAmmo(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_shootingDistance(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_walkSpeed(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_runSpeed(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_lowBatterySpeed(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_minDistance(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batteryIdleDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batteryWalkingDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batteryRunningDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batteryPrimaryWeaponDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batterySecondaryWeaponDrainRate(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_IsWalking(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_IsRunning(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_name(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_ReasoningStyleType(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_X(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_Y(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_Z(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_currentStateName(closeRangeEnforcer4,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_EnemyId(closeRangeEnforcer4,objectIndex(Index),Value).
%worldInformationManagerSensor_EnemyName(worldInformationManager,objectIndex(Index),Index1,Value).
%worldInformationManagerSensor_Distance(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_ID(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_SenderName(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_MessageState(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_ParametersText(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_X(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_Y(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_Z(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_TaskType(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_AssignedTo(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_IsTaken(worldInformationManager,objectIndex(Index),Index1,Value).
%worldInformationManagerSensor_TaskId(worldInformationManager,objectIndex(Index),Index1,Value).
% Predicates for Action invokation.
% applyAction(OrderOfExecution,ActionClassName).
% actionArgument(ActionOrder,ArgumentName, ArgumentValue).
