%For runtime instantiated GameObject, only the prefab mapping is provided. Use that one substituting the gameobject name accordingly.
 %Sensors.
%lumenSentinelSensor_CurrentHealth(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_IsDead(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_currentStateName(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Z(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Y(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_X(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_name(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyId(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_ReasoningStyleType(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_minBatteryBeforeRecharge(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_shootingDistance(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_batteryIdleDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_batteryWalkingDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_batteryRunningDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_batteryPrimaryWeaponDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_batterySecondaryWeaponDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_primaryAmmo(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_secondaryAmmo(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_minBatteryBeforeRecharge(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_primaryAmmo(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_secondaryAmmo(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_shootingDistance(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_walkSpeed(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_runSpeed(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_lowBatterySpeed(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_minDistance(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batteryIdleDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batteryWalkingDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batteryRunningDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batteryPrimaryWeaponDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_Resources_batterySecondaryWeaponDrainRate(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_IsWalking(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_IsRunning(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_name(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_ReasoningStyleType(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_X(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_Y(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_Z(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_currentStateName(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_EnemyStateController_EnemyId(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_HealthController_IsDead(overrideStalker6,objectIndex(Index),Value).
%lumenSentinelSensor_healthValue(overrideStalker6,objectIndex(Index),Value).
%worldInformationManagerSensor_EnemyName(worldInformationManager,objectIndex(Index),Index1,Value).
%worldInformationManagerSensor_Distance(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_ID(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_SenderName(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_MessageState(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_ParametersText(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_X(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_Y(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_Z(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_TaskType(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_AssignedTo(worldInformationManager,objectIndex(Index),Index1,Value).
%aiMessage_IsTaken(worldInformationManager,objectIndex(Index),Index1,Value).
%worldInformationManagerSensor_TaskId(worldInformationManager,objectIndex(Index),Index1,Value).
% Predicates for Action invokation.
% applyAction(OrderOfExecution,ActionClassName).
% actionArgument(ActionOrder,ArgumentName, ArgumentValue).
